version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  # app:
  #   build:
  #     dockerfile: dockerfiles/app.node.dockerfile
  #   ports:
  #     - '3000:3000'
  #   depends_on:
  #     - db
    

volumes:
  postgres_data:
